### ISSUE TITLE
Ticks labels for interaction plot (effects package)

### ISSUE THREAD

**Issue by davidcanarte** [clayford/effects_pkg#1]
Dear Clay 
I am using Effects package to plot results for an interaction between "counts of support" x "length of stay" on self-rated health (outcome)... I've been successful so far, but I have not been able to find a way to change ticks labels for "length of stay".  This is the code. 

plot(Effect(focal.predictors = c("Counts Support", "Length.Stay"), mod = my_model, 
            xlevels = list("Counts Support"= 0:4)), 
     rug = FALSE,
     style = "stacked",
     main = "Counts of Support x Length of Stay on SRH",
     axes = list(y=list(lab = "SRH (probablity)")), 
     xlab=("Counts of Support"))
dev.off()

**Comment by clayford** [comment]
Hi. I don't know enough about your data or plot to assist. Or at least I can't figure out how to help based just on your code. You may want to look at the [Predictor Effects Graphics Gallery](https://cran.r-project.org/web/packages/effects/vignettes/predictor-effects-gallery.pdf) vignette that comes with the effects package. I think a lot has changed with the effects package since I taught this workshop over 4 years ago.

**Comment by davidcanarte** [comment]
Thank you Clay. I think I found what I want.  Pag 32 (3.4.4.) 
https://rdrr.io/cran/effects/f/inst/doc/predictor-effects-gallery.pdf
